---
# Finish (post-deploy) tasks

- name: Loading irules content
  include_vars: irules.json

- name: Define irules
  bigip_irule_bigsuds:
    state: "{{ item.state | default('present') }}"
    name: "{{ item['name'].split('/')[-1] }}"
    content: "{{ item.content }}"
    partition: "{{ f5_partition }}"
    server: "{{ f5_server }}"
    user: "{{ f5_user }}"
    password: "{{ f5_pass }}"
    validate_certs: "{{ f5_ssl_validate }}"
  when: item.content is defined and item.content
  with_items: "{{ f5_irules | default([]) }}"
  delegate_to: "{{ groups.client[0] }}"

- name: Define virtual server
  bigip_virtual_server:
    state: present
    name: "{{ f5_vip_name }}"
    destination: "{{ f5_vip_address }}"
    port: "{{ f5_vip_port }}"
    pool: "{{ f5_pool_name }}"
    snat: "{{ f5_vip_snat | default(omit) }}"
    description: "{{ f5_vip_description }}"
    all_profiles: "{{ f5_vip_profiles }}"
    enabled_vlans: "{{ f5_vip_vlans }}"
    all_rules: "{{ f5_vip_irules }}"
    partition: "{{ f5_partition }}"
    server: "{{ f5_server }}"
    user: "{{ f5_user }}"
    password: "{{ f5_pass }}"
    validate_certs: "{{ f5_ssl_validate }}"
  delegate_to: "{{ groups.client[0] }}"

